services:
  # 1. Backend
  - type: web
    name: agenda-backend
    runtime: node
    region: frankfurt
    plan: free
    rootCommand: cd backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DB_DIALECT
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: defaultdb

  # 2. Frontend
  - type: static
    name: agenda-frontend
    runtime: static
    region: frankfurt
    plan: free
    rootCommand: cd frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: agenda-backend
          property: url