services:
  # ------------------------------------
  # 1. O BACKEND (Node.js Web Service)
  # ------------------------------------
  - type: web
    name: agenda-backend
    runtime: node
    region: frankfurt # Escolha a região mais próxima (ex: oregon ou frankfurt)
    plan: free
    rootCommand: cd backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DB_DIALECT
        value: mysql
      # Estas variáveis "sync: false" significam que o Render vai
      # abrir campos para você colar os dados do Aiven manualmente
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: defaultdb # Ou 'agenda', se mudou o nome no Aiven

  # ------------------------------------
  # 2. O FRONTEND (React Static Site)
  # ------------------------------------
  - type: static
    name: agenda-frontend
    runtime: static
    region: frankfurt
    plan: free
    rootCommand: cd frontend
    # Comando para instalar dependências e criar a pasta 'dist'
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      # Pega automaticamente a URL do backend que criamos acima
      - key: VITE_API_URL
        fromService:
          type: web
          name: agenda-backend
          property: url